name: fluid-page-cache
type: php
docroot: ~
no_project_mount: true
php_version: "7.2"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames:
    - v8.fluid-page-cache
    - v9.fluid-page-cache
    - v10.fluid-page-cache
additional_fqdns: []
provider: default
use_dns_when_possible: true
omit_containers:
    - dba
extra_services:
    - v8-data
    - v9-data
    - v10-data
